spring.application.name=biblioteca-infnet-api
spring.datasource.url=jdbc:mysql://localhost:3306/biblioteca_api
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

